server:
  port: ${port}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://xxx #公用配置
          username: xxx
          password: xxx

encrypt:
  key-store:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
