server:
  port: ${port}
security:
  basic:
    enabled: true
  user:
    name: chester
    password: chester

spring:
  cloud:
    config:
      server:
        git:
          uri: https://xxx #公用配置
          username: xxx
          password: xxx
          repos:
            simple:
              uri: https://xxx/simple
            special:
              pattern: special*/dev*, special*/test*
              uri: https://xxx/special
